version: "3"
services: 
  node_contas:
    build: node_contas
    depends_on:
      - db
    ports:
      - "3002:3002"
    volumes:
      - ./home/app
      - /home/app/node_modules
    environment:
      DB_HOST: db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P4SSW0rD
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: ProjFinalBanco
    ports:
      - "3308:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

